<a href="https://colab.research.google.com/github/Veer-Parikh/git_init_devopia/blob/main/Devopia_Analyse_Student_Scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/student-scores.csv')
df

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [5]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [6]:
df.shape

(2000, 17)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2000 non-null   int64
 1   first_name                  2000 non-null   object
 2   last_name                   2000 non-null   object
 3   email                       2000 non-null   object
 4   gender                      2000 non-null   object
 5   part_time_job               2000 non-null   bool
 6   absence_days                2000 non-null   int64
 7   extracurricular_activities  2000 non-null   bool
 8   weekly_self_study_hours     2000 non-null   int64
 9   career_aspiration           2000 non-null   object
 10  math_score                  2000 non-null   int64
 11  history_score               2000 non-null   int64
 12  physics_score               2000 non-null   int64
 13  chemistry_score             2000 non-null   int64
 14  biology_score               2000 non-null   int64
 15  english_score               2000 non-null   int64
 16  geography_score             2000 non-null   int64
dtypes: bool(2), int64(10), object(5)
memory usage: 238.4+ KB

In [8]:
df.describe()

,id,absence_days,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,1000.500000,3.665500,17.755500,83.452000,80.332000,81.336500,79.995000,79.58150,81.277500,80.888000
std,577.494589,2.629271,12.129604,13.224906,12.736046,12.539453,12.777895,13.72219,12.027087,11.637705
min,1.000000,0.000000,0.000000,40.000000,50.000000,50.000000,50.000000,30.00000,50.000000,60.000000
25%,500.750000,2.000000,5.000000,77.000000,69.750000,71.000000,69.000000,69.00000,72.000000,71.000000
50%,1000.500000,3.000000,18.000000,87.000000,82.000000,83.000000,81.000000,81.00000,83.000000,81.000000
75%,1500.250000,5.000000,28.000000,93.000000,91.000000,92.000000,91.000000,91.00000,91.000000,91.000000
max,2000.000000,10.000000,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,99.000000,100.000000

In [9]:
df.isnull().values.any()

False

In [10]:
# Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
#        'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
#        'career_aspiration', 'math_score', 'history_score', 'physics_score',
#        'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
#       dtype='object')

In [11]:
# prompt: from the df drop also columns other than numerical onces

df = df.drop(['first_name','gender', 'last_name', 'email'], axis=1)
df

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [12]:
# prompt: change male as 0 and female as 1 in gender,  true as 1 and false as 0 in part_time_job, extracurricular_activities

df['part_time_job'].replace([True, False], [1, 0], inplace=True)
df['extracurricular_activities'].replace([True, False], [1, 0], inplace=True)

df

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87
1,2,0,2,0,47,Doctor,90,86,96,100,90,88,90
2,3,0,9,1,13,Government Officer,81,97,95,96,65,77,94
3,4,0,5,0,3,Artist,71,74,88,80,89,63,86
4,5,0,5,0,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,2,0,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,0,2,0,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,0,5,0,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,1,10,1,5,Business Owner,51,96,72,89,95,88,75
1999,2000,0,5,0,27,Accountant,82,99,91,69,83,93,100

In [13]:
# prompt: career_aspiration unique entries in this column and what they are ?

unique_aspirations = df['career_aspiration'].unique()
print(f"Unique career aspirations: {unique_aspirations}")

Unique career aspirations: ['Lawyer' 'Doctor' 'Government Officer' 'Artist' 'Unknown'
 'Software Engineer' 'Teacher' 'Business Owner' 'Scientist' 'Banker'
 'Writer' 'Accountant' 'Designer' 'Construction Engineer' 'Game Developer'
 'Stock Investor' 'Real Estate Developer']

In [14]:
# prompt: percentage score  column focombined percentage of all columns (math_score	history_score	physics_score	chemistry_score	biology_score	english_score	geography_score )

df['total_score'] = df[['math_score', 'history_score', 'physics_score', 'chemistry_score', 'biology_score', 'english_score', 'geography_score']].sum(axis=1)
df['percentage_score'] = (df['total_score'] / 700) * 100
df

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,percentage_score
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,2,0,2,0,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,3,0,9,1,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,4,0,5,0,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,5,0,5,0,10,Unknown,84,77,65,65,80,74,76,521,74.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,2,0,30,Construction Engineer,83,77,84,73,75,84,82,558,79.714286
1996,1997,0,2,0,20,Software Engineer,89,65,73,80,87,67,73,534,76.285714
1997,1998,0,5,0,14,Software Engineer,97,85,63,93,68,94,78,578,82.571429
1998,1999,1,10,1,5,Business Owner,51,96,72,89,95,88,75,566,80.857143
1999,2000,0,5,0,27,Accountant,82,99,91,69,83,93,100,617,88.142857

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2000 non-null   int64
 1   part_time_job               2000 non-null   int64
 2   absence_days                2000 non-null   int64
 3   extracurricular_activities  2000 non-null   int64
 4   weekly_self_study_hours     2000 non-null   int64
 5   career_aspiration           2000 non-null   object
 6   math_score                  2000 non-null   int64
 7   history_score               2000 non-null   int64
 8   physics_score               2000 non-null   int64
 9   chemistry_score             2000 non-null   int64
 10  biology_score               2000 non-null   int64
 11  english_score               2000 non-null   int64
 12  geography_score             2000 non-null   int64
 13  total_score                 2000 non-null   int64
 14  percentage_score            2000 non-null   float64
dtypes: float64(1), int64(13), object(1)
memory usage: 234.5+ KB

In [16]:
df.describe()

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,percentage_score
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,0.158000,3.665500,0.20400,17.755500,83.452000,80.332000,81.336500,79.995000,79.58150,81.277500,80.888000,566.862500,80.980357
std,577.494589,0.364832,2.629271,0.40307,12.129604,13.224906,12.736046,12.539453,12.777895,13.72219,12.027087,11.637705,42.295568,6.042224
min,1.000000,0.000000,0.000000,0.00000,0.000000,40.000000,50.000000,50.000000,50.000000,30.00000,50.000000,60.000000,414.000000,59.142857
25%,500.750000,0.000000,2.000000,0.00000,5.000000,77.000000,69.750000,71.000000,69.000000,69.00000,72.000000,71.000000,541.000000,77.285714
50%,1000.500000,0.000000,3.000000,0.00000,18.000000,87.000000,82.000000,83.000000,81.000000,81.00000,83.000000,81.000000,567.000000,81.000000
75%,1500.250000,0.000000,5.000000,0.00000,28.000000,93.000000,91.000000,92.000000,91.000000,91.00000,91.000000,91.000000,593.000000,84.714286
max,2000.000000,1.000000,10.000000,1.00000,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,99.000000,100.000000,673.000000,96.142857

In [17]:
df

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,percentage_score
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,2,0,2,0,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,3,0,9,1,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,4,0,5,0,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,5,0,5,0,10,Unknown,84,77,65,65,80,74,76,521,74.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,2,0,30,Construction Engineer,83,77,84,73,75,84,82,558,79.714286
1996,1997,0,2,0,20,Software Engineer,89,65,73,80,87,67,73,534,76.285714
1997,1998,0,5,0,14,Software Engineer,97,85,63,93,68,94,78,578,82.571429
1998,1999,1,10,1,5,Business Owner,51,96,72,89,95,88,75,566,80.857143
1999,2000,0,5,0,27,Accountant,82,99,91,69,83,93,100,617,88.142857

In [18]:
# prompt: if absence_days is less then equal to 3 replace with 1, if more then 3 and greater than equal 6 replace with 2 if the  absence_days is less then 10 replace with 3 else 4

import numpy as np
def categorize_absences(x):
    if x <= 3:
        return 1
    elif 3 < x <= 6:
        return 2
    elif 6 < x < 10:
        return 3
    else:
        return 4

df['category'] = df['absence_days'].apply(categorize_absences)
print(df)

        id  part_time_job  absence_days  extracurricular_activities  \
0        1              0             3                           0
1        2              0             2                           0
2        3              0             9                           1
3        4              0             5                           0
4        5              0             5                           0
...    ...            ...           ...                         ...
1995  1996              0             2                           0
1996  1997              0             2                           0
1997  1998              0             5                           0
1998  1999              1            10                           1
1999  2000              0             5                           0

      weekly_self_study_hours      career_aspiration  math_score  \
0                          27                 Lawyer          73
1                          47                 Doctor          90
2                          13     Government Officer          81
3                           3                 Artist          71
4                          10                Unknown          84
...                       ...                    ...         ...
1995                       30  Construction Engineer          83
1996                       20      Software Engineer          89
1997                       14      Software Engineer          97
1998                        5         Business Owner          51
1999                       27             Accountant          82

      history_score  physics_score  chemistry_score  biology_score  \
0                81             93               97             63
1                86             96              100             90
2                97             95               96             65
3                74             88               80             89
4                77             65               65             80
...             ...            ...              ...            ...
1995             77             84               73             75
1996             65             73               80             87
1997             85             63               93             68
1998             96             72               89             95
1999             99             91               69             83

      english_score  geography_score  total_score  percentage_score  category
0                80               87          574         82.000000         1
1                88               90          640         91.428571         1
2                77               94          605         86.428571         3
3                63               86          551         78.714286         2
4                74               76          521         74.428571         2
...             ...              ...          ...               ...       ...
1995             84               82          558         79.714286         1
1996             67               73          534         76.285714         1
1997             94               78          578         82.571429         2
1998             88               75          566         80.857143         4
1999             93              100          617         88.142857         2

[2000 rows x 16 columns]

In [19]:
df

,id,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,percentage_score,category
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87,574,82.000000,1
1,2,0,2,0,47,Doctor,90,86,96,100,90,88,90,640,91.428571,1
2,3,0,9,1,13,Government Officer,81,97,95,96,65,77,94,605,86.428571,3
3,4,0,5,0,3,Artist,71,74,88,80,89,63,86,551,78.714286,2
4,5,0,5,0,10,Unknown,84,77,65,65,80,74,76,521,74.428571,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,2,0,30,Construction Engineer,83,77,84,73,75,84,82,558,79.714286,1
1996,1997,0,2,0,20,Software Engineer,89,65,73,80,87,67,73,534,76.285714,1
1997,1998,0,5,0,14,Software Engineer,97,85,63,93,68,94,78,578,82.571429,2
1998,1999,1,10,1,5,Business Owner,51,96,72,89,95,88,75,566,80.857143,4
1999,2000,0,5,0,27,Accountant,82,99,91,69,83,93,100,617,88.142857,2

In [20]:
# prompt: one hot encode category ( to 4 columns 1,2,3,4), drop absence_days

import pandas as pd
df = pd.get_dummies(df, columns=['category'], prefix='category_absence_days')
df.drop('absence_days', axis=1, inplace=True)
df

,id,part_time_job,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,percentage_score,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4
0,1,0,0,27,Lawyer,73,81,93,97,63,80,87,574,82.000000,True,False,False,False
1,2,0,0,47,Doctor,90,86,96,100,90,88,90,640,91.428571,True,False,False,False
2,3,0,1,13,Government Officer,81,97,95,96,65,77,94,605,86.428571,False,False,True,False
3,4,0,0,3,Artist,71,74,88,80,89,63,86,551,78.714286,False,True,False,False
4,5,0,0,10,Unknown,84,77,65,65,80,74,76,521,74.428571,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,0,30,Construction Engineer,83,77,84,73,75,84,82,558,79.714286,True,False,False,False
1996,1997,0,0,20,Software Engineer,89,65,73,80,87,67,73,534,76.285714,True,False,False,False
1997,1998,0,0,14,Software Engineer,97,85,63,93,68,94,78,578,82.571429,False,True,False,False
1998,1999,1,1,5,Business Owner,51,96,72,89,95,88,75,566,80.857143,False,False,False,True
1999,2000,0,0,27,Accountant,82,99,91,69,83,93,100,617,88.142857,False,True,False,False

In [21]:
def percentage_score(x):
    if x <= 60:
        return 1
    elif 60 < x <= 70:
        return 2
    elif 70 < x < 80:
        return 3
    elif 80 < x < 90:
        return 4
    else:
        return 5

df['category_percentage_score'] = df['percentage_score'].apply(percentage_score)
print(df)

        id  part_time_job  extracurricular_activities  \
0        1              0                           0
1        2              0                           0
2        3              0                           1
3        4              0                           0
4        5              0                           0
...    ...            ...                         ...
1995  1996              0                           0
1996  1997              0                           0
1997  1998              0                           0
1998  1999              1                           1
1999  2000              0                           0

      weekly_self_study_hours      career_aspiration  math_score  \
0                          27                 Lawyer          73
1                          47                 Doctor          90
2                          13     Government Officer          81
3                           3                 Artist          71
4                          10                Unknown          84
...                       ...                    ...         ...
1995                       30  Construction Engineer          83
1996                       20      Software Engineer          89
1997                       14      Software Engineer          97
1998                        5         Business Owner          51
1999                       27             Accountant          82

      history_score  physics_score  chemistry_score  biology_score  \
0                81             93               97             63
1                86             96              100             90
2                97             95               96             65
3                74             88               80             89
4                77             65               65             80
...             ...            ...              ...            ...
1995             77             84               73             75
1996             65             73               80             87
1997             85             63               93             68
1998             96             72               89             95
1999             99             91               69             83

      english_score  geography_score  total_score  percentage_score  \
0                80               87          574         82.000000
1                88               90          640         91.428571
2                77               94          605         86.428571
3                63               86          551         78.714286
4                74               76          521         74.428571
...             ...              ...          ...               ...
1995             84               82          558         79.714286
1996             67               73          534         76.285714
1997             94               78          578         82.571429
1998             88               75          566         80.857143
1999             93              100          617         88.142857

      category_absence_days_1  category_absence_days_2  \
0                        True                    False
1                        True                    False
2                       False                    False
3                       False                     True
4                       False                     True
...                       ...                      ...
1995                     True                    False
1996                     True                    False
1997                    False                     True
1998                    False                    False
1999                    False                     True

      category_absence_days_3  category_absence_days_4  \
0                       False                    False
1                       False                    False
2                        True                    False
3                       False                    False
4                       False                    False
...                       ...                      ...
1995                    False                    False
1996                    False                    False
1997                    False                    False
1998                    False                     True
1999                    False                    False

      category_percentage_score
0                             4
1                             5
2                             4
3                             3
4                             3
...                         ...
1995                          3
1996                          3
1997                          4
1998                          4
1999                          4

[2000 rows x 19 columns]

In [22]:
# prompt: percentage_score drop

df.drop('percentage_score', axis=1, inplace=True)
print(df)

        id  part_time_job  extracurricular_activities  \
0        1              0                           0
1        2              0                           0
2        3              0                           1
3        4              0                           0
4        5              0                           0
...    ...            ...                         ...
1995  1996              0                           0
1996  1997              0                           0
1997  1998              0                           0
1998  1999              1                           1
1999  2000              0                           0

      weekly_self_study_hours      career_aspiration  math_score  \
0                          27                 Lawyer          73
1                          47                 Doctor          90
2                          13     Government Officer          81
3                           3                 Artist          71
4                          10                Unknown          84
...                       ...                    ...         ...
1995                       30  Construction Engineer          83
1996                       20      Software Engineer          89
1997                       14      Software Engineer          97
1998                        5         Business Owner          51
1999                       27             Accountant          82

      history_score  physics_score  chemistry_score  biology_score  \
0                81             93               97             63
1                86             96              100             90
2                97             95               96             65
3                74             88               80             89
4                77             65               65             80
...             ...            ...              ...            ...
1995             77             84               73             75
1996             65             73               80             87
1997             85             63               93             68
1998             96             72               89             95
1999             99             91               69             83

      english_score  geography_score  total_score  category_absence_days_1  \
0                80               87          574                     True
1                88               90          640                     True
2                77               94          605                    False
3                63               86          551                    False
4                74               76          521                    False
...             ...              ...          ...                      ...
1995             84               82          558                     True
1996             67               73          534                     True
1997             94               78          578                    False
1998             88               75          566                    False
1999             93              100          617                    False

      category_absence_days_2  category_absence_days_3  \
0                       False                    False
1                       False                    False
2                       False                     True
3                        True                    False
4                        True                    False
...                       ...                      ...
1995                    False                    False
1996                    False                    False
1997                     True                    False
1998                    False                    False
1999                     True                    False

      category_absence_days_4  category_percentage_score
0                       False                          4
1                       False                          5
2                       False                          4
3                       False                          3
4                       False                          3
...                       ...                        ...
1995                    False                          3
1996                    False                          3
1997                    False                          4
1998                     True                          4
1999                    False                          4

[2000 rows x 18 columns]

In [23]:
# prompt: change true and false to 1 and 0 incategory_absence_days_1	category_absence_days_2	category_absence_days_3	category_absence_days_4

df['category_absence_days_1'].replace([True, False], [1, 0], inplace=True)
df['category_absence_days_2'].replace([True, False], [1, 0], inplace=True)
df['category_absence_days_3'].replace([True, False], [1, 0], inplace=True)
df['category_absence_days_4'].replace([True, False], [1, 0], inplace=True)

In [24]:
def weekly_self_study_hours(x):
    if x <= 10:
        return 1
    elif 10 < x <= 20:
        return 2
    elif 20 < x <=30:
        return 3
    elif 30 < x <=40:
        return 4
    else:
        return 5

df['category_weekly_self_study_hours'] = df['weekly_self_study_hours'].apply(weekly_self_study_hours)
print(df)

        id  part_time_job  extracurricular_activities  \
0        1              0                           0
1        2              0                           0
2        3              0                           1
3        4              0                           0
4        5              0                           0
...    ...            ...                         ...
1995  1996              0                           0
1996  1997              0                           0
1997  1998              0                           0
1998  1999              1                           1
1999  2000              0                           0

      weekly_self_study_hours      career_aspiration  math_score  \
0                          27                 Lawyer          73
1                          47                 Doctor          90
2                          13     Government Officer          81
3                           3                 Artist          71
4                          10                Unknown          84
...                       ...                    ...         ...
1995                       30  Construction Engineer          83
1996                       20      Software Engineer          89
1997                       14      Software Engineer          97
1998                        5         Business Owner          51
1999                       27             Accountant          82

      history_score  physics_score  chemistry_score  biology_score  \
0                81             93               97             63
1                86             96              100             90
2                97             95               96             65
3                74             88               80             89
4                77             65               65             80
...             ...            ...              ...            ...
1995             77             84               73             75
1996             65             73               80             87
1997             85             63               93             68
1998             96             72               89             95
1999             99             91               69             83

      english_score  geography_score  total_score  category_absence_days_1  \
0                80               87          574                        1
1                88               90          640                        1
2                77               94          605                        0
3                63               86          551                        0
4                74               76          521                        0
...             ...              ...          ...                      ...
1995             84               82          558                        1
1996             67               73          534                        1
1997             94               78          578                        0
1998             88               75          566                        0
1999             93              100          617                        0

      category_absence_days_2  category_absence_days_3  \
0                           0                        0
1                           0                        0
2                           0                        1
3                           1                        0
4                           1                        0
...                       ...                      ...
1995                        0                        0
1996                        0                        0
1997                        1                        0
1998                        0                        0
1999                        1                        0

      category_absence_days_4  category_percentage_score  \
0                           0                          4
1                           0                          5
2                           0                          4
3                           0                          3
4                           0                          3
...                       ...                        ...
1995                        0                          3
1996                        0                          3
1997                        0                          4
1998                        1                          4
1999                        0                          4

      category_weekly_self_study_hours
0                                    3
1                                    5
2                                    2
3                                    1
4                                    1
...                                ...
1995                                 3
1996                                 2
1997                                 2
1998                                 1
1999                                 3

[2000 rows x 19 columns]

In [25]:
df

,id,part_time_job,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4,category_percentage_score,category_weekly_self_study_hours
0,1,0,0,27,Lawyer,73,81,93,97,63,80,87,574,1,0,0,0,4,3
1,2,0,0,47,Doctor,90,86,96,100,90,88,90,640,1,0,0,0,5,5
2,3,0,1,13,Government Officer,81,97,95,96,65,77,94,605,0,0,1,0,4,2
3,4,0,0,3,Artist,71,74,88,80,89,63,86,551,0,1,0,0,3,1
4,5,0,0,10,Unknown,84,77,65,65,80,74,76,521,0,1,0,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,0,0,30,Construction Engineer,83,77,84,73,75,84,82,558,1,0,0,0,3,3
1996,1997,0,0,20,Software Engineer,89,65,73,80,87,67,73,534,1,0,0,0,3,2
1997,1998,0,0,14,Software Engineer,97,85,63,93,68,94,78,578,0,1,0,0,4,2
1998,1999,1,1,5,Business Owner,51,96,72,89,95,88,75,566,0,0,0,1,4,1
1999,2000,0,0,27,Accountant,82,99,91,69,83,93,100,617,0,1,0,0,4,3

In [26]:
# prompt: drop id

df.drop('id', axis=1, inplace=True)

In [27]:
df.columns

Index(['part_time_job', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score',
       'category_absence_days_1', 'category_absence_days_2',
       'category_absence_days_3', 'category_absence_days_4',
       'category_percentage_score', 'category_weekly_self_study_hours'],
      dtype='object')

In [28]:
# prompt: category_percentage_score', 'category_weekly_self_study_hours one hot encode

import pandas as pd
df = pd.get_dummies(df, columns=['category_weekly_self_study_hours'], prefix='category_weekly_self_study_hours')
df

,part_time_job,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,...,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4,category_percentage_score,category_weekly_self_study_hours_1,category_weekly_self_study_hours_2,category_weekly_self_study_hours_3,category_weekly_self_study_hours_4,category_weekly_self_study_hours_5
0,0,0,27,Lawyer,73,81,93,97,63,80,...,1,0,0,0,4,False,False,True,False,False
1,0,0,47,Doctor,90,86,96,100,90,88,...,1,0,0,0,5,False,False,False,False,True
2,0,1,13,Government Officer,81,97,95,96,65,77,...,0,0,1,0,4,False,True,False,False,False
3,0,0,3,Artist,71,74,88,80,89,63,...,0,1,0,0,3,True,False,False,False,False
4,0,0,10,Unknown,84,77,65,65,80,74,...,0,1,0,0,3,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,30,Construction Engineer,83,77,84,73,75,84,...,1,0,0,0,3,False,False,True,False,False
1996,0,0,20,Software Engineer,89,65,73,80,87,67,...,1,0,0,0,3,False,True,False,False,False
1997,0,0,14,Software Engineer,97,85,63,93,68,94,...,0,1,0,0,4,False,True,False,False,False
1998,1,1,5,Business Owner,51,96,72,89,95,88,...,0,0,0,1,4,True,False,False,False,False
1999,0,0,27,Accountant,82,99,91,69,83,93,...,0,1,0,0,4,False,False,True,False,False

In [29]:
# prompt: 	category_percentage_score_1	category_percentage_score_2	category_percentage_score_3	category_percentage_score_4	category_percentage_score_5	category_weekly_self_study_hours_1	category_weekly_self_study_hours_2	category_weekly_self_study_hours_3	category_weekly_self_study_hours_4	category_weekly_self_study_hours_5 convert to 0 and 1 instead of true and false


df['category_weekly_self_study_hours_1'] = df['category_weekly_self_study_hours_1'].astype(int)
df['category_weekly_self_study_hours_2'] = df['category_weekly_self_study_hours_2'].astype(int)
df['category_weekly_self_study_hours_3'] = df['category_weekly_self_study_hours_3'].astype(int)
df['category_weekly_self_study_hours_4'] = df['category_weekly_self_study_hours_4'].astype(int)
df['category_weekly_self_study_hours_5'] = df['category_weekly_self_study_hours_5'].astype(int)

df

,part_time_job,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,...,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4,category_percentage_score,category_weekly_self_study_hours_1,category_weekly_self_study_hours_2,category_weekly_self_study_hours_3,category_weekly_self_study_hours_4,category_weekly_self_study_hours_5
0,0,0,27,Lawyer,73,81,93,97,63,80,...,1,0,0,0,4,0,0,1,0,0
1,0,0,47,Doctor,90,86,96,100,90,88,...,1,0,0,0,5,0,0,0,0,1
2,0,1,13,Government Officer,81,97,95,96,65,77,...,0,0,1,0,4,0,1,0,0,0
3,0,0,3,Artist,71,74,88,80,89,63,...,0,1,0,0,3,1,0,0,0,0
4,0,0,10,Unknown,84,77,65,65,80,74,...,0,1,0,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,30,Construction Engineer,83,77,84,73,75,84,...,1,0,0,0,3,0,0,1,0,0
1996,0,0,20,Software Engineer,89,65,73,80,87,67,...,1,0,0,0,3,0,1,0,0,0
1997,0,0,14,Software Engineer,97,85,63,93,68,94,...,0,1,0,0,4,0,1,0,0,0
1998,1,1,5,Business Owner,51,96,72,89,95,88,...,0,0,0,1,4,1,0,0,0,0
1999,0,0,27,Accountant,82,99,91,69,83,93,...,0,1,0,0,4,0,0,1,0,0

In [30]:
df.columns

Index(['part_time_job', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score',
       'category_absence_days_1', 'category_absence_days_2',
       'category_absence_days_3', 'category_absence_days_4',
       'category_percentage_score', 'category_weekly_self_study_hours_1',
       'category_weekly_self_study_hours_2',
       'category_weekly_self_study_hours_3',
       'category_weekly_self_study_hours_4',
       'category_weekly_self_study_hours_5'],
      dtype='object')

In [31]:
# prompt: weekly_self_study_hours drop

df = df.drop('weekly_self_study_hours', axis=1)

In [32]:
df

,part_time_job,extracurricular_activities,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,...,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4,category_percentage_score,category_weekly_self_study_hours_1,category_weekly_self_study_hours_2,category_weekly_self_study_hours_3,category_weekly_self_study_hours_4,category_weekly_self_study_hours_5
0,0,0,Lawyer,73,81,93,97,63,80,87,...,1,0,0,0,4,0,0,1,0,0
1,0,0,Doctor,90,86,96,100,90,88,90,...,1,0,0,0,5,0,0,0,0,1
2,0,1,Government Officer,81,97,95,96,65,77,94,...,0,0,1,0,4,0,1,0,0,0
3,0,0,Artist,71,74,88,80,89,63,86,...,0,1,0,0,3,1,0,0,0,0
4,0,0,Unknown,84,77,65,65,80,74,76,...,0,1,0,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,Construction Engineer,83,77,84,73,75,84,82,...,1,0,0,0,3,0,0,1,0,0
1996,0,0,Software Engineer,89,65,73,80,87,67,73,...,1,0,0,0,3,0,1,0,0,0
1997,0,0,Software Engineer,97,85,63,93,68,94,78,...,0,1,0,0,4,0,1,0,0,0
1998,1,1,Business Owner,51,96,72,89,95,88,75,...,0,0,0,1,4,1,0,0,0,0
1999,0,0,Accountant,82,99,91,69,83,93,100,...,0,1,0,0,4,0,0,1,0,0

In [33]:
df.columns

Index(['part_time_job', 'extracurricular_activities', 'career_aspiration',
       'math_score', 'history_score', 'physics_score', 'chemistry_score',
       'biology_score', 'english_score', 'geography_score', 'total_score',
       'category_absence_days_1', 'category_absence_days_2',
       'category_absence_days_3', 'category_absence_days_4',
       'category_percentage_score', 'category_weekly_self_study_hours_1',
       'category_weekly_self_study_hours_2',
       'category_weekly_self_study_hours_3',
       'category_weekly_self_study_hours_4',
       'category_weekly_self_study_hours_5'],
      dtype='object')

In [34]:
# prompt: data frame should contain following fields-'part_time_job', 'extracurricular_activities', 'career_aspiration',
#        'math_score', 'history_score', 'physics_score', 'chemistry_score',
#        'biology_score', 'english_score', 'geography_score', 'total_score',
#        'category_absence_days_1', 'category_absence_days_2',
#        'category_absence_days_3', 'category_absence_days_4',
#        'category_p
X= df[['part_time_job', 'extracurricular_activities',
       'category_absence_days_1', 'category_absence_days_2',
       'category_absence_days_3', 'category_absence_days_4',
        'category_weekly_self_study_hours_1',
       'category_weekly_self_study_hours_2', 'category_weekly_self_study_hours_3',
       'category_weekly_self_study_hours_4', 'category_weekly_self_study_hours_5']]


y=df[['category_percentage_score']]

In [35]:
# prompt: train,test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [36]:
X_train.shape

(1400, 11)

In [37]:
y_train.shape

(1400, 1)

In [38]:
y_train

      category_percentage_score
836                           4
575                           4
557                           3
1235                          4
1360                          5
...                         ...
1130                          3
1294                          4
860                           3
1459                          3
1126                          3

[1400 rows x 1 columns]

In [39]:
def tranform_to(a):
  b = np.zeros((len(a), 5))
  for k in range(len(a)):
    if a[k]==1:
      b[k][0]=1
    elif a[k]==2:
      b[k][1]=1
    elif a[k]==3:
      b[k][2]=1
    elif a[k]==4:
      b[k][3]=1
    elif a[k]==5:
      b[k][4]=1
  return b

In [40]:
from keras.models import Sequential
from keras.layers import Dense,Flatten

model = Sequential()

model.add(Dense(5, activation='sigmoid', input_shape=(11,)))

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 60

=================================================================
Total params: 60 (240.00 Byte)
Trainable params: 60 (240.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [41]:
import numpy as np
y_train_as_np = np.array(y_train)

y_train_f=tranform_to(y_train_as_np)
model.fit(X_train,y_train_f , epochs=25)

Epoch 1/25
44/44 [==============================] - 1s 2ms/step - loss: 1.5470 - accuracy: 0.3686
Epoch 2/25
44/44 [==============================] - 0s 2ms/step - loss: 1.4551 - accuracy: 0.4371
Epoch 3/25
44/44 [==============================] - 0s 2ms/step - loss: 1.3787 - accuracy: 0.4729
Epoch 4/25
44/44 [==============================] - 0s 2ms/step - loss: 1.3159 - accuracy: 0.4943
Epoch 5/25
44/44 [==============================] - 0s 2ms/step - loss: 1.2640 - accuracy: 0.4979
Epoch 6/25
44/44 [==============================] - 0s 2ms/step - loss: 1.2207 - accuracy: 0.4993
Epoch 7/25
44/44 [==============================] - 0s 2ms/step - loss: 1.1850 - accuracy: 0.5014
Epoch 8/25
44/44 [==============================] - 0s 2ms/step - loss: 1.1551 - accuracy: 0.5007
Epoch 9/25
44/44 [==============================] - 0s 2ms/step - loss: 1.1301 - accuracy: 0.5014
Epoch 10/25
44/44 [==============================] - 0s 2ms/step - loss: 1.1091 - accuracy: 0.5157
Epoch 11/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0914 - accuracy: 0.5150
Epoch 12/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0764 - accuracy: 0.5150
Epoch 13/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0634 - accuracy: 0.5150
Epoch 14/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0524 - accuracy: 0.5179
Epoch 15/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0428 - accuracy: 0.5171
Epoch 16/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0347 - accuracy: 0.5214
Epoch 17/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0271 - accuracy: 0.5300
Epoch 18/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0206 - accuracy: 0.5350
Epoch 19/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0146 - accuracy: 0.5414
Epoch 20/25
44/44 [==============================] - 0s 2ms/step - loss: 1.0094 - accuracy: 0.5457
Epoch 21/25
44/44 [==============================] - 0s 3ms/step - loss: 1.0045 - accuracy: 0.5457
Epoch 22/25
44/44 [==============================] - 0s 3ms/step - loss: 1.0000 - accuracy: 0.5493
Epoch 23/25
44/44 [==============================] - 0s 3ms/step - loss: 0.9960 - accuracy: 0.5507
Epoch 24/25
44/44 [==============================] - 0s 3ms/step - loss: 0.9924 - accuracy: 0.5507
Epoch 25/25
44/44 [==============================] - 0s 3ms/step - loss: 0.9889 - accuracy: 0.5507

In [42]:
# prompt: test the model using accuracy_score

import numpy as np
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
y_test_as_np = np.array(y_test)
y_test_f=tranform_to(y_test_as_np)

max_values = np.max(y_pred, axis=1)
y_pred = np.where(y_pred == max_values[:, np.newaxis], 1, 0)

print(accuracy_score(y_test_f, y_pred))

19/19 [==============================] - 0s 2ms/step
0.5216666666666666

In [43]:
import pickle


with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

In [44]:
df

,part_time_job,extracurricular_activities,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,...,category_absence_days_1,category_absence_days_2,category_absence_days_3,category_absence_days_4,category_percentage_score,category_weekly_self_study_hours_1,category_weekly_self_study_hours_2,category_weekly_self_study_hours_3,category_weekly_self_study_hours_4,category_weekly_self_study_hours_5
0,0,0,Lawyer,73,81,93,97,63,80,87,...,1,0,0,0,4,0,0,1,0,0
1,0,0,Doctor,90,86,96,100,90,88,90,...,1,0,0,0,5,0,0,0,0,1
2,0,1,Government Officer,81,97,95,96,65,77,94,...,0,0,1,0,4,0,1,0,0,0
3,0,0,Artist,71,74,88,80,89,63,86,...,0,1,0,0,3,1,0,0,0,0
4,0,0,Unknown,84,77,65,65,80,74,76,...,0,1,0,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,Construction Engineer,83,77,84,73,75,84,82,...,1,0,0,0,3,0,0,1,0,0
1996,0,0,Software Engineer,89,65,73,80,87,67,73,...,1,0,0,0,3,0,1,0,0,0
1997,0,0,Software Engineer,97,85,63,93,68,94,78,...,0,1,0,0,4,0,1,0,0,0
1998,1,1,Business Owner,51,96,72,89,95,88,75,...,0,0,0,1,4,1,0,0,0,0
1999,0,0,Accountant,82,99,91,69,83,93,100,...,0,1,0,0,4,0,0,1,0,0

In [45]:
# prompt: drop carreeer aspiration

df_drop=df.drop('career_aspiration', axis=1)

In [46]:
df_drop=df.drop('career_aspiration', axis=1)

# Calculate the correlation matrix
correlation_matrix = df_drop.corr()

# Print the correlation matrix
print(correlation_matrix)

                                    part_time_job  extracurricular_activities  \
part_time_job                            1.000000                   -0.008382
extracurricular_activities              -0.008382                    1.000000
math_score                              -0.185573                   -0.052968
history_score                           -0.110774                    0.012526
physics_score                           -0.123929                   -0.009333
chemistry_score                         -0.089219                   -0.003007
biology_score                           -0.004072                   -0.010062
english_score                           -0.098809                   -0.003428
geography_score                         -0.030352                   -0.040877
total_score                             -0.192846                   -0.031952
category_absence_days_1                 -0.165546                   -0.015989
category_absence_days_2                  0.028255                   -0.000910
category_absence_days_3                  0.129593                    0.014020
category_absence_days_4                  0.134320                    0.018440
category_percentage_score               -0.167877                   -0.018702
category_weekly_self_study_hours_1       0.232939                    0.011283
category_weekly_self_study_hours_2      -0.081387                    0.054841
category_weekly_self_study_hours_3      -0.097293                   -0.004247
category_weekly_self_study_hours_4      -0.084017                   -0.059412
category_weekly_self_study_hours_5      -0.019504                   -0.026606

                                    math_score  history_score  physics_score  \
part_time_job                        -0.185573      -0.110774      -0.123929
extracurricular_activities           -0.052968       0.012526      -0.009333
math_score                            1.000000       0.147247       0.115719
history_score                         0.147247       1.000000       0.048478
physics_score                         0.115719       0.048478       1.000000
chemistry_score                       0.127131       0.121498       0.126163
biology_score                         0.081298       0.088502       0.132280
english_score                         0.134831       0.147193       0.054314
geography_score                       0.049672       0.065751       0.103126
total_score                           0.508116       0.486900       0.472104
category_absence_days_1               0.173261       0.098189       0.119949
category_absence_days_2              -0.003683      -0.005006      -0.053259
category_absence_days_3              -0.137733      -0.097404      -0.044271
category_absence_days_4              -0.193012      -0.072606      -0.104936
category_percentage_score             0.449128       0.427879       0.419268
category_weekly_self_study_hours_1   -0.411001      -0.219247      -0.142727
category_weekly_self_study_hours_2    0.109402      -0.004741      -0.028966
category_weekly_self_study_hours_3    0.153729       0.057498       0.033287
category_weekly_self_study_hours_4    0.181220       0.161762       0.116579
category_weekly_self_study_hours_5    0.099872       0.137969       0.145457

                                    chemistry_score  biology_score  \
part_time_job                             -0.089219      -0.004072
extracurricular_activities                -0.003007      -0.010062
math_score                                 0.127131       0.081298
history_score                              0.121498       0.088502
physics_score                              0.126163       0.132280
chemistry_score                            1.000000       0.119992
biology_score                              0.119992       1.000000
english_score                              0.068341       0.074227
geography_score                            0.065430       0.106526
total_score                                0.492216       0.502391
category_absence_days_1                    0.070776       0.091911
category_absence_days_2                   -0.003487      -0.046035
category_absence_days_3                   -0.075908      -0.030426
category_absence_days_4                   -0.043618      -0.074667
category_percentage_score                  0.453371       0.455992
category_weekly_self_study_hours_1        -0.126777      -0.109104
category_weekly_self_study_hours_2        -0.041572      -0.041724
category_weekly_self_study_hours_3         0.026355      -0.003264
category_weekly_self_study_hours_4         0.115850       0.128595
category_weekly_self_study_hours_5         0.151812       0.152082

                                    english_score  geography_score  \
part_time_job                           -0.098809        -0.030352
extracurricular_activities              -0.003428        -0.040877
math_score                               0.134831         0.049672
history_score                            0.147193         0.065751
physics_score                            0.054314         0.103126
chemistry_score                          0.068341         0.065430
biology_score                            0.074227         0.106526
english_score                            1.000000         0.072250
geography_score                          0.072250         1.000000
total_score                              0.451550         0.415929
category_absence_days_1                  0.080978        -0.002768
category_absence_days_2                 -0.014346         0.013476
category_absence_days_3                 -0.091062        -0.021734
category_absence_days_4                 -0.020969         0.011913
category_percentage_score                0.404871         0.356656
category_weekly_self_study_hours_1      -0.224979        -0.070289
category_weekly_self_study_hours_2       0.046190        -0.040651
category_weekly_self_study_hours_3       0.039528        -0.045944
category_weekly_self_study_hours_4       0.138782         0.126270
category_weekly_self_study_hours_5       0.126321         0.157939

                                    total_score  category_absence_days_1  \
part_time_job                         -0.192846                -0.165546
extracurricular_activities            -0.031952                -0.015989
math_score                             0.508116                 0.173261
history_score                          0.486900                 0.098189
physics_score                          0.472104                 0.119949
chemistry_score                        0.492216                 0.070776
biology_score                          0.502391                 0.091911
english_score                          0.451550                 0.080978
geography_score                        0.415929                -0.002768
total_score                            1.000000                 0.192769
category_absence_days_1                0.192769                 1.000000
category_absence_days_2               -0.034809                -0.695044
category_absence_days_3               -0.150200                -0.423862
category_absence_days_4               -0.153411                -0.248012
category_percentage_score              0.891748                 0.177296
category_weekly_self_study_hours_1    -0.393858                -0.243841
category_weekly_self_study_hours_2     0.000045                 0.106940
category_weekly_self_study_hours_3     0.080752                 0.102207
category_weekly_self_study_hours_4     0.290863                 0.051797
category_weekly_self_study_hours_5     0.290480                 0.049469

                                    category_absence_days_2  \
part_time_job                                      0.028255
extracurricular_activities                        -0.000910
math_score                                        -0.003683
history_score                                     -0.005006
physics_score                                     -0.053259
chemistry_score                                   -0.003487
biology_score                                     -0.046035
english_score                                     -0.014346
geography_score                                    0.013476
total_score                                       -0.034809
category_absence_days_1                           -0.695044
category_absence_days_2                            1.000000
category_absence_days_3                           -0.220437
category_absence_days_4                           -0.128983
category_percentage_score                         -0.038456
category_weekly_self_study_hours_1                 0.021042
category_weekly_self_study_hours_2                -0.041766
category_weekly_self_study_hours_3                 0.018201
category_weekly_self_study_hours_4                 0.006679
category_weekly_self_study_hours_5                -0.022503

                                    category_absence_days_3  \
part_time_job                                      0.129593
extracurricular_activities                         0.014020
math_score                                        -0.137733
history_score                                     -0.097404
physics_score                                     -0.044271
chemistry_score                                   -0.075908
biology_score                                     -0.030426
english_score                                     -0.091062
geography_score                                   -0.021734
total_score                                       -0.150200
category_absence_days_1                           -0.423862
category_absence_days_2                           -0.220437
category_absence_days_3                            1.000000
category_absence_days_4                           -0.078658
category_percentage_score                         -0.115583
category_weekly_self_study_hours_1                 0.206156
category_weekly_self_study_hours_2                -0.058495
category_weekly_self_study_hours_3                -0.113954
category_weekly_self_study_hours_4                -0.049150
category_weekly_self_study_hours_5                -0.034763

                                    category_absence_days_4  \
part_time_job                                      0.134320
extracurricular_activities                         0.018440
math_score                                        -0.193012
history_score                                     -0.072606
physics_score                                     -0.104936
chemistry_score                                   -0.043618
biology_score                                     -0.074667
english_score                                     -0.020969
geography_score                                    0.011913
total_score                                       -0.153411
category_absence_days_1                           -0.248012
category_absence_days_2                           -0.128983
category_absence_days_3                           -0.078658
category_absence_days_4                            1.000000
category_percentage_score                         -0.162780
category_weekly_self_study_hours_1                 0.218085
category_weekly_self_study_hours_2                -0.075883
category_weekly_self_study_hours_3                -0.106186
category_weekly_self_study_hours_4                -0.061887
category_weekly_self_study_hours_5                -0.016110

                                    category_percentage_score  \
part_time_job                                       -0.167877
extracurricular_activities                          -0.018702
math_score                                           0.449128
history_score                                        0.427879
physics_score                                        0.419268
chemistry_score                                      0.453371
biology_score                                        0.455992
english_score                                        0.404871
geography_score                                      0.356656
total_score                                          0.891748
category_absence_days_1                              0.177296
category_absence_days_2                             -0.038456
category_absence_days_3                             -0.115583
category_absence_days_4                             -0.162780
category_percentage_score                            1.000000
category_weekly_self_study_hours_1                  -0.348832
category_weekly_self_study_hours_2                   0.005172
category_weekly_self_study_hours_3                   0.055892
category_weekly_self_study_hours_4                   0.262120
category_weekly_self_study_hours_5                   0.278283

                                    category_weekly_self_study_hours_1  \
part_time_job                                                 0.232939
extracurricular_activities                                    0.011283
math_score                                                   -0.411001
history_score                                                -0.219247
physics_score                                                -0.142727
chemistry_score                                              -0.126777
biology_score                                                -0.109104
english_score                                                -0.224979
geography_score                                              -0.070289
total_score                                                  -0.393858
category_absence_days_1                                      -0.243841
category_absence_days_2                                       0.021042
category_absence_days_3                                       0.206156
category_absence_days_4                                       0.218085
category_percentage_score                                    -0.348832
category_weekly_self_study_hours_1                            1.000000
category_weekly_self_study_hours_2                           -0.371318
category_weekly_self_study_hours_3                           -0.426921
category_weekly_self_study_hours_4                           -0.315551
category_weekly_self_study_hours_5                           -0.108287

                                    category_weekly_self_study_hours_2  \
part_time_job                                                -0.081387
extracurricular_activities                                    0.054841
math_score                                                    0.109402
history_score                                                -0.004741
physics_score                                                -0.028966
chemistry_score                                              -0.041572
biology_score                                                -0.041724
english_score                                                 0.046190
geography_score                                              -0.040651
total_score                                                   0.000045
category_absence_days_1                                       0.106940
category_absence_days_2                                      -0.041766
category_absence_days_3                                      -0.058495
category_absence_days_4                                      -0.075883
category_percentage_score                                     0.005172
category_weekly_self_study_hours_1                           -0.371318
category_weekly_self_study_hours_2                            1.000000
category_weekly_self_study_hours_3                           -0.311176
category_weekly_self_study_hours_4                           -0.230000
category_weekly_self_study_hours_5                           -0.078929

                                    category_weekly_self_study_hours_3  \
part_time_job                                                -0.097293
extracurricular_activities                                   -0.004247
math_score                                                    0.153729
history_score                                                 0.057498
physics_score                                                 0.033287
chemistry_score                                               0.026355
biology_score                                                -0.003264
english_score                                                 0.039528
geography_score                                              -0.045944
total_score                                                   0.080752
category_absence_days_1                                       0.102207
category_absence_days_2                                       0.018201
category_absence_days_3                                      -0.113954
category_absence_days_4                                      -0.106186
category_percentage_score                                     0.055892
category_weekly_self_study_hours_1                           -0.426921
category_weekly_self_study_hours_2                           -0.311176
category_weekly_self_study_hours_3                            1.000000
category_weekly_self_study_hours_4                           -0.264442
category_weekly_self_study_hours_5                           -0.090748

                                    category_weekly_self_study_hours_4  \
part_time_job                                                -0.084017
extracurricular_activities                                   -0.059412
math_score                                                    0.181220
history_score                                                 0.161762
physics_score                                                 0.116579
chemistry_score                                               0.115850
biology_score                                                 0.128595
english_score                                                 0.138782
geography_score                                               0.126270
total_score                                                   0.290863
category_absence_days_1                                       0.051797
category_absence_days_2                                       0.006679
category_absence_days_3                                      -0.049150
category_absence_days_4                                      -0.061887
category_percentage_score                                     0.262120
category_weekly_self_study_hours_1                           -0.315551
category_weekly_self_study_hours_2                           -0.230000
category_weekly_self_study_hours_3                           -0.264442
category_weekly_self_study_hours_4                            1.000000
category_weekly_self_study_hours_5                           -0.067075

                                    category_weekly_self_study_hours_5
part_time_job                                                -0.019504
extracurricular_activities                                   -0.026606
math_score                                                    0.099872
history_score                                                 0.137969
physics_score                                                 0.145457
chemistry_score                                               0.151812
biology_score                                                 0.152082
english_score                                                 0.126321
geography_score                                               0.157939
total_score                                                   0.290480
category_absence_days_1                                       0.049469
category_absence_days_2                                      -0.022503
category_absence_days_3                                      -0.034763
category_absence_days_4                                      -0.016110
category_percentage_score                                     0.278283
category_weekly_self_study_hours_1                           -0.108287
category_weekly_self_study_hours_2                           -0.078929

In [47]:
!pip install colabcode
!ngrok config add-authtoken 2erxMJBy1CkjlslheA5woJTIceB_4imVLWCkSFkv7qwqaWS7Y

Collecting colabcode
  Downloading colabcode-0.3.0-py3-none-any.whl (5.0 kB)
Collecting pyngrok>=5.0.0 (from colabcode)
  Downloading pyngrok-7.1.6-py3-none-any.whl (22 kB)
Collecting nest-asyncio==1.4.3 (from colabcode)
  Downloading nest_asyncio-1.4.3-py3-none-any.whl (5.3 kB)
Collecting uvicorn==0.13.1 (from colabcode)
  Downloading uvicorn-0.13.1-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.0 MB/s eta 0:00:00
Collecting jupyterlab==3.0.7 (from colabcode)
  Downloading jupyterlab-3.0.7-py3-none-any.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 35.7 MB/s eta 0:00:00
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (7.34.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (24.0)
Requirement already satisfied: tornado>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (6.3.3)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (5.7.2)
Collecting jupyterlab-server~=2.0 (from jupyterlab==3.0.7->colabcode)
  Downloading jupyterlab_server-2.26.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: jupyter-server~=1.2 in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (1.24.0)
Collecting nbclassic~=0.2 (from jupyterlab==3.0.7->colabcode)
  Downloading nbclassic-0.5.6-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 40.3 MB/s eta 0:00:00
Requirement already satisfied: jinja2>=2.10 in /usr/local/lib/python3.10/dist-packages (from jupyterlab==3.0.7->colabcode) (3.1.3)
Collecting click==7.* (from uvicorn==0.13.1->colabcode)
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 5.6 MB/s eta 0:00:00
Collecting h11>=0.8 (from uvicorn==0.13.1->colabcode)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.7 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.10/dist-packages (from pyngrok>=5.0.0->colabcode) (6.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.10->jupyterlab==3.0.7->colabcode) (2.1.5)
Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (3.7.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (23.1.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (6.1.12)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (6.5.4)
Requirement already satisfied: nbformat>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (5.10.4)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.20.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (23.2.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.18.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (5.7.1)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.7.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core->jupyterlab==3.0.7->colabcode) (4.2.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (2.14.0)
Collecting json5>=0.9.0 (from jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode)
  Downloading json5-0.9.25-py3-none-any.whl (30 kB)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (4.19.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (2.31.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from nbclassic~=0.2->jupyterlab==3.0.7->colabcode) (0.2.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic~=0.2->jupyterlab==3.0.7->colabcode) (0.2.4)
INFO: pip is looking at multiple versions of nbclassic to determine which version is compatible with other requirements. This could take a while.
Collecting nbclassic~=0.2 (from jupyterlab==3.0.7->colabcode)
  Downloading nbclassic-0.5.5-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 40.0 MB/s eta 0:00:00
  Downloading nbclassic-0.5.4-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 53.7 MB/s eta 0:00:00
  Downloading nbclassic-0.5.3-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 44.4 MB/s eta 0:00:00
  Downloading nbclassic-0.5.2-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 48.3 MB/s eta 0:00:00
  Downloading nbclassic-0.5.1-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 36.3 MB/s eta 0:00:00
  Downloading nbclassic-0.4.8-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 60.6 MB/s eta 0:00:00
  Downloading nbclassic-0.4.7-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 34.1 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of nbclassic to determine which version is compatible with other requirements. This could take a while.
  Downloading nbclassic-0.4.6-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 27.5 MB/s eta 0:00:00
  Downloading nbclassic-0.4.5-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 17.7 MB/s eta 0:00:00
  Downloading nbclassic-0.4.4-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 60.6 MB/s eta 0:00:00
  Downloading nbclassic-0.4.3-py3-none-any.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 39.7 MB/s eta 0:00:00
  Downloading nbclassic-0.4.2-py3-none-any.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 31.8 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading nbclassic-0.4.0-py3-none-any.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 23.4 MB/s eta 0:00:00
  Downloading nbclassic-0.3.7-py3-none-any.whl (13 kB)
Requirement already satisfied: notebook<7 in /usr/local/lib/python3.10/dist-packages (from nbclassic~=0.2->jupyterlab==3.0.7->colabcode) (6.5.5)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (67.7.2)
Collecting jedi>=0.16 (from ipython->jupyterlab==3.0.7->colabcode)
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 48.3 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (3.0.43)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->jupyterlab==3.0.7->colabcode) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (3.6)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->jupyterlab==3.0.7->colabcode) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (0.18.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.10/dist-packages (from jupyter-client>=6.1.12->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (2.8.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (4.9.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (4.12.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.3.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.5.1)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.2.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.2.0->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (2.19.1)
INFO: pip is looking at multiple versions of notebook to determine which version is compatible with other requirements. This could take a while.
Collecting notebook<7 (from nbclassic~=0.2->jupyterlab==3.0.7->colabcode)
  Downloading notebook-6.5.6-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.8/529.8 kB 35.7 MB/s eta 0:00:00
  Downloading notebook-6.5.4-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.8/529.8 kB 39.5 MB/s eta 0:00:00
  Downloading notebook-6.5.3-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 41.4 MB/s eta 0:00:00
  Downloading notebook-6.5.2-py3-none-any.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.1/439.1 kB 34.7 MB/s eta 0:00:00
  Downloading notebook-6.5.1-py3-none-any.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.1/439.1 kB 38.4 MB/s eta 0:00:00
  Downloading notebook-6.4.13-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 43.1 MB/s eta 0:00:00
  Downloading notebook-6.4.12-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 61.9 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of notebook to determine which version is compatible with other requirements. This could take a while.
  Downloading notebook-6.4.11-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 49.0 MB/s eta 0:00:00
  Downloading notebook-6.4.10-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 19.7 MB/s eta 0:00:00
  Downloading notebook-6.4.9-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 28.7 MB/s eta 0:00:00
  Downloading notebook-6.4.8-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 32.3 MB/s eta 0:00:00
  Downloading notebook-6.4.7-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 51.3 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading notebook-6.4.6-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 61.8 MB/s eta 0:00:00
  Downloading notebook-6.4.5-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 48.0 MB/s eta 0:00:00
Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/dist-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.0.7->colabcode) (5.5.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->jupyterlab==3.0.7->colabcode) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab==3.0.7->colabcode) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->jupyterlab-server~=2.0->jupyterlab==3.0.7->colabcode) (2024.2.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (21.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.1->jupyter-client>=6.1.12->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.16.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (2.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert>=6.4.4->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (0.5.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server~=1.2->jupyterlab==3.0.7->colabcode) (2.22)
Installing collected packages: pyngrok, nest-asyncio, json5, jedi, h11, click, uvicorn, notebook, jupyterlab-server, nbclassic, jupyterlab, colabcode
  Attempting uninstall: nest-asyncio
    Found existing installation: nest-asyncio 1.6.0
    Uninstalling nest-asyncio-1.6.0:
      Successfully uninstalled nest-asyncio-1.6.0
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
  Attempting uninstall: notebook
    Found existing installation: notebook 6.5.5
    Uninstalling notebook-6.5.5:
      Successfully uninstalled notebook-6.5.5
  Attempting uninstall: nbclassic
    Found existing installation: nbclassic 1.0.0
    Uninstalling nbclassic-1.0.0:
      Successfully uninstalled nbclassic-1.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.2.5 requires click>=8.0, but you have click 7.1.2 which is incompatible.
dask 2023.8.1 requires click>=8.0, but you have click 7.1.2 which is incompatible.
distributed 2023.8.1 requires click>=8.0, but you have click 7.1.2 which is incompatible.
fiona 1.9.6 requires click~=8.0, but you have click 7.1.2 which is incompatible.
google-colab 1.0.0 requires notebook==6.5.5, but you have notebook 6.4.5 which is incompatible.
pip-tools 6.13.0 requires click>=8, but you have click 7.1.2 which is incompatible.
Successfully installed click-7.1.2 colabcode-0.3.0 h11-0.14.0 jedi-0.19.1 json5-0.9.25 jupyterlab-3.0.7 jupyterlab-server-2.26.0 nbclassic-0.3.7 nest-asyncio-1.4.3 notebook-6.4.5 pyngrok-7.1.6 uvicorn-0.13.1
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [48]:
!pip install fastapi

Collecting fastapi
  Downloading fastapi-0.110.1-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.9/91.9 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from fastapi) (2.6.4)
Collecting starlette<0.38.0,>=0.37.2 (from fastapi)
  Downloading starlette-0.37.2-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from fastapi) (4.11.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.16.3)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from starlette<0.38.0,>=0.37.2->fastapi) (3.7.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.38.0,>=0.37.2->fastapi) (3.6)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.38.0,>=0.37.2->fastapi) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.38.0,>=0.37.2->fastapi) (1.2.0)
Installing collected packages: starlette, fastapi
Successfully installed fastapi-0.110.1 starlette-0.37.2

In [49]:
!pip install uvicorn

Requirement already satisfied: uvicorn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: click==7.* in /usr/local/lib/python3.10/dist-packages (from uvicorn) (7.1.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn) (0.14.0)

In [50]:
# prompt: X=[0,0,1,0,0,0,1,0,0,0,0]
# run model on this

import numpy as np
X=np.array([
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0
])

y_pred = model.predict(X.reshape(1, -1))
max_values = np.max(y_pred, axis=1)
y_pred = np.where(y_pred == max_values[:, np.newaxis], 1, 0)
print( y_pred)

1/1 [==============================] - 0s 35ms/step
[[0 0 1 0 0]]

In [51]:
a= [0]
b=[1]
c=[1,0,0,0]
d= [1,0,0,0,0]
X = np.concatenate((a,b,c,d ))
print(X[5])
print(X.shape)
print(model.input_shape)

0
(11,)
(None, 11)

In [ ]:
import pickle
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import numpy as np
from colabcode import ColabCode

# Define request body schema using Pydantic
class PredictionData(BaseModel):
    part_time_job: int
    extracurricular_activities: int
    absence_days: int
    weekly_self_study_hours: int

# Load your pickled model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

def part_time_job(x):
    if x==0:
        return [0]
    else:
        return [1]

def extracurricular_activities(x):
    if x==0:
        return [0]
    else:
        return [1]

# Categorize absence days
def categorize_absences(x):
    if x <= 3:
        return [1,0,0,0]
    elif 3 < x <= 6:
        return [0,1,0,0]
    elif 6 < x < 10:
        return [0,0,1,0]
    else:
        return [0,0,0,1]

# Categorize weekly self-study hours
def weekly_self_study_hours(x):
    if x <= 10:
        return [1,0,0,0,0]
    elif 10 < x <= 20:
        return [0,1,0,0,0]
    elif 20 < x <= 30:
        return [0,0,1,0,0]
    elif 30 < x <= 40:
        return [0,0,0,1,0]
    else:
        return [0,0,0,0,1]

# Create an instance of FastAPI
app = FastAPI()

origins = [
    "http://localhost.tiangolo.com",
    "https://localhost.tiangolo.com",
    "http://localhost",
    "http://localhost:3001",
    "http://localhost:8080",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def test():
  return f"Hello World"

# Endpoint for making predictions
@app.post("/predict/")
async def predict(data: PredictionData):
    try:
        # Prepare input features for prediction
        part_time_job_array = part_time_job(data.part_time_job)
        extracurricular_activities_array = extracurricular_activities(data.extracurricular_activities)
        absence_days_array = categorize_absences(data.absence_days)
        weekly_self_study_hours_array = weekly_self_study_hours(data.weekly_self_study_hours)

        # Concatenate the arrays
        X = np.concatenate((
            part_time_job_array,
            extracurricular_activities_array,
            absence_days_array,  # Ensure 2D array
            weekly_self_study_hours_array # Ensure 2D array
        ))
        X = X.reshape((1, 11))

        # Make prediction
        prediction = model.predict(X)

        # Convert predicted probabilities to binary values
        max_values = np.max(prediction, axis=1)
        prediction_binary = np.where(prediction == max_values[:, np.newaxis], 1, 0)
        prediction = prediction_binary.tolist()
        index_of_1 = prediction[0].index(1)
        print("Index of 1:", index_of_1)
        return {"prediction": index_of_1}
    except Exception as e:
        # Log the error with detailed information
        import traceback
        traceback.print_exc()
        # Return an HTTP 500 error response with a detailed error message
        raise HTTPException(status_code=500, detail=f"An error occurred during prediction: {str(e)}")

# Run the FastAPI app with ColabCode
cc = ColabCode(port=12000, code=False)
cc.run_app(app=app)

INFO:     Started server process [204]
INFO:uvicorn.error:Started server process [204]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)

Public URL: NgrokTunnel: "https://bc15-35-227-115-82.ngrok-free.app" -> "http://localhost:12000"
INFO:     115.112.43.148:0 - "GET / HTTP/1.1" 200 OK
INFO:     115.112.43.148:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     115.112.43.148:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     115.112.43.148:0 - "GET /openapi.json HTTP/1.1" 200 OK
1/1 [==============================] - 0s 52ms/step
Index of 1: 3
INFO:     115.112.43.148:0 - "POST /predict/ HTTP/1.1" 200 OK
1/1 [==============================] - 0s 23ms/step
Index of 1: 2
INFO:     54.86.50.139:0 - "POST /predict/%0A HTTP/1.1" 200 OK
INFO:     115.112.43.148:0 - "OPTIONS /predict/ HTTP/1.1" 400 Bad Request